iso_3166_countries = {
    'AL': 'Albania',
    'AT': 'Austria',
    'BE': 'Belgium',
    'BG': 'Bulgaria',
    'BY': 'Belarus',
    'CH': 'Switzerland',
    'CZ': 'Czech Republic',
    'DE': 'Germany',
    'DK': 'Denmark',
    'ES': 'Spain',
    'FI': 'Finland',
    'FR': 'France',
    'GB': 'United Kingdom',
    'GR': 'Greece',
    'HR': 'Croatia',
    'HU': 'Hungary',
    'IE': 'Ireland',
    'IT': 'Italy',
    'KO': 'Kosova',
    'NL': 'the Netherlands',
    'NO': 'Norway',
    'PL': 'Poland',
    'PT': 'Portugal',
    'RO': 'Romania',
    'RS': 'Serbia',
    'SE': 'Sweden',
    'TR': 'Turkey',
    'UA': 'Ukraine',
    'EU': 'Europe',
    'ZZ': 'International', # ZZ is a "User-assigned code element" and free to use: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#ZZ
    'UK': 'United Kingdom'  # historical reasons™
}

supported_languages = [
    "bg",
    "ca",
    "cs",
    "de",
    "el",
    "en",
    "es",
    "fr",
    "it",
    "nl",
    "no",
]

months = {
    '01': 'January',
    '02': 'February',
    '03': 'March',
    '04': 'April',
    '05': 'May',
    '06': 'June',
    '07': 'July',
    '08': 'August',
    '09': 'September',
    '10': 'October',
    '11': 'November',
    '12': 'December',
}
