iso_3166_countries = {
    'AT': 'Austria',
    'BE': 'Belgium',
    'BG': 'Bulgaria',
    'BY': 'Belarus',
    'CH': 'Switzerland',
    'CZ': 'Czech Republic',
    'DE': 'Germany',
    'DK': 'Denmark',
    'ES': 'Spain',
    'FR': 'France',
    'GB': 'United Kingdom',
    'GR': 'Greece',
    'HR': 'Croatia',
    'HU': 'Hungary',
    'IE': 'Ireland',
    'IT': 'Italy',
    'KO': 'Kosova',
    'NL': 'the Netherlands',
    'NO': 'Norway',
    'PL': 'Poland',
    'PT': 'Portugal',
    'RO': 'Romania',
    'RS': 'Serbia',
    'SE': 'Sweden',
    'SQ': 'Albania',
    'UA': 'Ukraine',
    'UK': 'United Kingdom'  # historical reasons™
}

iso_639_languages = {
    "BG": "Bulgarian",
    "BS": "Bosnian",
    "CS": "Czech",
    "DA": "Danish",
    "DE": "German",
    "EN": "English",
    "ES": "Spanish",
    "FI": "Finnish",
    "FR": "French",
    "IT": "Italian",
    "HR": "Croatian",
    "HU": "Hungarian",
    "NL": "Dutch",
    "PL": "Polish",
    "PT": "Portuguese",
    "RO": "Romanian",
    "RU": "Russian",
    "SQ": "Albanian",
    "SR": "Serbian",
    "SV": "Swedish",
    "UK": "Ukrainian",
}

months = {
    '01': 'January',
    '02': 'February',
    '03': 'March',
    '04': 'April',
    '05': 'May',
    '06': 'June',
    '07': 'July',
    '08': 'August',
    '09': 'September',
    '10': 'October',
    '11': 'November',
    '12': 'December',
}
