image: mweimann/fossevents-cicd:1.0.0

stages:
  - build
  - deploy

build_website:
  stage: build
  variables:
      GIT_SUBMODULE_STRATEGY: recursive
  artifacts:
    paths:
      - build/
  script:
    - pipenv install
    - make tmp/npm_deps_token
    - make --jobs=2
  only:
    - main

deploy_to_test:
  stage: deploy
  dependencies:
    - build_website
  script:
    - lftp -e "set ftp:ssl-allow no; mirror --parallel --no-symlinks -R build/ /" -u $TEST_FTP_USER,$TEST_FTP_PASS $TEST_FTP_HOST || true
  only:
    - test

deploy_to_live:
  stage: deploy
  dependencies:
    - build_website
  script:
    - lftp -e "set ftp:ssl-allow no; mirror --parallel --no-symlinks -R build/ /" -u $LIVE_FTP_USER,$LIVE_FTP_PASS $LIVE_FTP_HOST || true
  only:
    - main
