#!/usr/bin/env python3

import csv
import os
import subprocess
import sys
from tempfile import NamedTemporaryFile

if len(sys.argv) < 3:
    print("param(s) missing; usage: ./fe file line")
    sys.exit(1)

editor = os.getenv("EDITOR")
infile = sys.argv[1]
editline = int(sys.argv[2])
outrows = []

with open(infile, "r") as f:
    reader = csv.DictReader(f, delimiter="	")
    line = 1

    for row in reader:
        line += 1
        row_data = row

        if line == editline:
            with NamedTemporaryFile(mode="r+") as tempfile:
                for k, v in row.items():
                    tempfile.write(f"{k}: {v}\n")

                tempfile.flush()
                p = subprocess.Popen([editor, tempfile.name])
                p.wait()

                tempfile.seek(0)
                values = {} 

                for templine in tempfile:
                    [column_name, value] = templine.split(":", maxsplit=1)
                    values[column_name.strip()] = value.strip()

                row_data = values

        outrows.append(row_data)

with open(infile, "w") as outfile:
    writer = csv.DictWriter(outfile, outrows[0].keys(), delimiter="	")
    writer.writeheader()
    writer.writerows(outrows)
